-- snowflake_sql/01_database_schemas.sql
-- Database, Schemas, Warehouse, Roles
-- Idempotent: IF NOT EXISTS ensures safe re-runs

-- 1. Database
CREATE DATABASE IF NOT EXISTS IODP_DC_${ENV};
USE DATABASE IODP_DC_${ENV};

-- 2. Schemas
CREATE SCHEMA IF NOT EXISTS RAW_STAGE COMMENT = 'External stage, file format, pipe objects';
CREATE SCHEMA IF NOT EXISTS SILVER    COMMENT = 'Unified wide table loaded by Snowpipe';
CREATE SCHEMA IF NOT EXISTS GOLD      COMMENT = 'Aggregated Dynamic Tables for BI';

-- 3. Warehouse
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH_DC_${ENV}
  WAREHOUSE_SIZE      = 'XSMALL'
  AUTO_SUSPEND        = 60
  AUTO_RESUME         = TRUE
  MAX_CLUSTER_COUNT   = 1
  MIN_CLUSTER_COUNT   = 1
  COMMENT             = 'Download Channel compute warehouse';

-- 4. Roles
CREATE ROLE IF NOT EXISTS IODP_DC_LOAD_${ENV}
  COMMENT = 'Snowpipe load role - INSERT only';
CREATE ROLE IF NOT EXISTS IODP_DC_TRANSFORM_${ENV}
  COMMENT = 'Dynamic Table refresh role';
CREATE ROLE IF NOT EXISTS IODP_DC_READER_${ENV}
  COMMENT = 'BI / downstream read-only role';

-- 5. Role hierarchy → SYSADMIN
GRANT ROLE IODP_DC_LOAD_${ENV}      TO ROLE SYSADMIN;
GRANT ROLE IODP_DC_TRANSFORM_${ENV}  TO ROLE SYSADMIN;
GRANT ROLE IODP_DC_READER_${ENV}     TO ROLE SYSADMIN;

-- 6. Warehouse grants
GRANT USAGE ON WAREHOUSE COMPUTE_WH_DC_${ENV} TO ROLE IODP_DC_LOAD_${ENV};
GRANT USAGE ON WAREHOUSE COMPUTE_WH_DC_${ENV} TO ROLE IODP_DC_TRANSFORM_${ENV};
GRANT USAGE ON WAREHOUSE COMPUTE_WH_DC_${ENV} TO ROLE IODP_DC_READER_${ENV};

-- 7. Database grants
GRANT USAGE ON DATABASE IODP_DC_${ENV} TO ROLE IODP_DC_LOAD_${ENV};
GRANT USAGE ON DATABASE IODP_DC_${ENV} TO ROLE IODP_DC_TRANSFORM_${ENV};
GRANT USAGE ON DATABASE IODP_DC_${ENV} TO ROLE IODP_DC_READER_${ENV};

-- 8. Schema grants
GRANT USAGE ON SCHEMA RAW_STAGE TO ROLE IODP_DC_LOAD_${ENV};
GRANT USAGE ON SCHEMA SILVER    TO ROLE IODP_DC_LOAD_${ENV};
GRANT USAGE ON SCHEMA SILVER    TO ROLE IODP_DC_TRANSFORM_${ENV};
GRANT USAGE ON SCHEMA SILVER    TO ROLE IODP_DC_READER_${ENV};
GRANT USAGE ON SCHEMA GOLD      TO ROLE IODP_DC_TRANSFORM_${ENV};
GRANT USAGE ON SCHEMA GOLD      TO ROLE IODP_DC_READER_${ENV};
